module.exports = {
  management: [
    "Leadership",
    "Project Management",
    "Strategic Planning",
    "Team Building",
    "Conflict Resolution",
    "Change Management",
    "Decision Making",
    "Strategic Leadership",
    "Team Collaboration",
  ],
  teaching: [
    "Classroom Management",
    "Curriculum Development",
    "Teaching Mathematics",
    "Language Instruction",
    "Educational Technology",
    "Science Education",
    "History Teaching",
    "Art Education",
    "Physical Education",
  ],
  account: [
    "Financial Analysis",
    "Taxation",
    "Auditing",
    "Budgeting",
    "Financial Reporting",
    "Bookkeeping",
    "Payroll",
    "Tax Planning",
    "Cost Management",
  ],
  backend: [
    "Node.js",
    "Ruby on Rails",
    "Python (Django)",
    "ASP.NET",
    "Express.js",
  ],
  frontend: ["CSS", "React", "Angular", "Bootstrap", "Sass"],
  webd: ["HTML", "JavaScript", "PHP", "jQuery", "Vue.js"],
  android: ["Java", "Kotlin", "C#", "Swift", "Flutter", "Android Studio"],
};
